#!/bin/bash
# =============================================================================
# rust-brain — Apply DevOps Migrations
# =============================================================================
# Applies numbered migrations from scripts/migrations/ against Postgres.
# These are infrastructure-level schema changes (column additions, index
# creation, auxiliary tables) that run BEFORE the sqlx migrations in
# services/api/migrations/.
#
# Called automatically by start.sh as Phase 2.5.
# Can also be run standalone:
#   bash scripts/apply-devops-migrations.sh
#   bash scripts/apply-devops-migrations.sh --dry-run
#
# Safety:
#   - Idempotent: skips already-applied migrations
#   - Tracks migrations in _devops_migrations table
#   - Each migration runs in a transaction where possible
#   - Exits on first failure (no partial apply)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MIGRATIONS_DIR="$PROJECT_DIR/scripts/migrations"

# Load .env if present
if [ -f "$PROJECT_DIR/.env" ]; then
    set -a
    # shellcheck disable=SC1091
    source "$PROJECT_DIR/.env"
    set +a
fi

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Verify Postgres is reachable
if ! docker-compose exec -T postgres pg_isready -U "${POSTGRES_USER:-rustbrain}" -d "${POSTGRES_DB:-rustbrain}" > /dev/null 2>&1; then
    log_error "Postgres is not ready. Start it first with: docker-compose up -d postgres"
    exit 1
fi

# Create _devops_migrations tracking table if it doesn't exist.
log_info "Ensuring _devops_migrations tracking table exists..."
docker-compose exec -T postgres psql -U "${POSTGRES_USER:-rustbrain}" -d "${POSTGRES_DB:-rustbrain}" > /dev/null 2>&1 <<'SQL'
CREATE TABLE IF NOT EXISTS _devops_migrations (
    version INTEGER PRIMARY KEY,
    description TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    execution_time_ms INTEGER
);
SQL
log_ok "Migration tracking table ready"

# List applied migrations
APPLIED=$(docker-compose exec -T postgres psql -U "${POSTGRES_USER:-rustbrain}" -d "${POSTGRES_DB:-rustbrain}" -t -A -c \
    "SELECT version FROM _devops_migrations WHERE success = true ORDER BY version;" 2>/dev/null || echo "")

# Discover pending migrations (sorted by filename = chronological)
PENDING=()
APPLIED_COUNT=0
PENDING_COUNT=0

for migration_file in "$MIGRATIONS_DIR"/*.sql; do
    [ -f "$migration_file" ] || continue

    # Extract version from filename: 001_add_generated_by.sql → 1
    basename=$(basename "$migration_file")
    version=$(echo "$basename" | grep -oP '^\d+' || true)

    if [ -z "$version" ]; then
        log_warn "Skipping malformed migration file: $basename"
        continue
    fi

    # Strip leading zeros for comparison: 001 → 1
    version_int=$((10#$version))

    # Check if already applied
    if echo "$APPLIED" | grep -q "^${version_int}$"; then
        APPLIED_COUNT=$((APPLIED_COUNT + 1))
        continue
    fi

    PENDING+=("$migration_file")
    PENDING_COUNT=$((PENDING_COUNT + 1))
done

if [ "$APPLIED_COUNT" -gt 0 ]; then
    log_info "$APPLIED_COUNT devops migration(s) already applied"
fi

if [ "$PENDING_COUNT" -eq 0 ]; then
    log_ok "No pending devops migrations"
    exit 0
fi

log_info "Found $PENDING_COUNT pending devops migration(s)"

# Apply pending migrations
for migration_file in "${PENDING[@]}"; do
    basename=$(basename "$migration_file")
    version=$(echo "$basename" | grep -oP '^\d+')
    version_int=$((10#$version))
    # Extract description from filename: 001_add_generated_by.sql → add generated by
    description=$(echo "$basename" | sed "s/^${version}_//" | sed 's/\.sql$//' | tr '_' ' ')

    if [ "$DRY_RUN" = true ]; then
        log_warn "[DRY-RUN] Would apply: $basename"
        continue
    fi

    log_info "Applying: $basename"

    START_TIME=$(date +%s%N)

    # Apply the migration
    if docker-compose exec -T postgres psql -U "${POSTGRES_USER:-rustbrain}" -d "${POSTGRES_DB:-rustbrain}" \
        -v ON_ERROR_STOP=1 \
        -f - < "$migration_file" > /dev/null 2>&1; then

        END_TIME=$(date +%s%N)
        EXECUTION_MS=$(( (END_TIME - START_TIME) / 1000000 ))

        # Record in tracking table
        docker-compose exec -T postgres psql -U "${POSTGRES_USER:-rustbrain}" -d "${POSTGRES_DB:-rustbrain}" > /dev/null 2>&1 <<SQL
INSERT INTO _devops_migrations (version, description, success, execution_time_ms)
VALUES (${version_int}, '${description}', true, ${EXECUTION_MS})
ON CONFLICT (version) DO UPDATE SET success = true, applied_at = NOW(), execution_time_ms = ${EXECUTION_MS};
SQL
        log_ok "Applied: $basename (${EXECUTION_MS}ms)"
    else
        # Record failure
        docker-compose exec -T postgres psql -U "${POSTGRES_USER:-rustbrain}" -d "${POSTGRES_DB:-rustbrain}" > /dev/null 2>&1 <<SQL
INSERT INTO _devops_migrations (version, description, success)
VALUES (${version_int}, '${description}', false)
ON CONFLICT (version) DO UPDATE SET success = false, applied_at = NOW();
SQL
        log_error "Failed to apply: $basename"
        log_error "Fix the migration and re-run, or manually mark as resolved in _devops_migrations"
        exit 1
    fi
done

log_ok "All $PENDING_COUNT pending devops migration(s) applied successfully"
